{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "incidentxbot.fullname" . }}
  labels:
    {{- include "incidentxbot.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      app: {{- include "incidentxbot.selectorLabels" . | nindent 6 }}
{{- end }}
