version: '3.9'
services:
  incidentxbot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['./wait-for-it.sh', 'db:5432', '--', 'python3', 'main.py']
    depends_on:
      - incidentxbot_db
    environment:
      # env var example
      INCIDENTS_DIGEST_CHANNEL: 'prod-incidents'
      SLACK_APP_TOKEN: 'xapp-1-...'
      SLACK_BOT_TOKEN: 'xoxb-...'
      SLACK_USER_TOKEN: 'xoxp-...'
      POSTGRES_HOST: db
      POSTGRES_DB: incidentxbot
      POSTGRES_USER: incidentxbot
      POSTGRES_PASSWORD: somepasswordxx
      POSTGRES_PORT: 5432
      INCIDENT_AUTO_GROUP_INVITE_ENABLED: 'false'
      INCIDENT_AUTO_GROUP_INVITE_GROUP_NAME: ''
      INCIDENT_EXTERNAL_PROVIDERS_ENABLED: 'false'
      INCIDENT_EXTERNAL_PROVIDERS_LIST: 'github'
      INCIDENT_AUTO_CREATE_FROM_REACT_ENABLED: 'false'
      INCIDENT_AUTO_CREATE_FROM_REACT_EMOJI_NAME: 'incidentx'
      STATUSPAGE_INTEGRATION_ENABLED: 'false'
      STATUSPAGE_API_KEY: 'github'
      STATUSPAGE_PAGE_ID: ''
      PAGERDUTY_INTEGRATION_ENABLED: 'false'
      PAGERDUTY_API_TOKEN: ''
      PAGERDUTY_API_USERNAME: ''
      STATUSPAGE_URL: ''
      AUTH0_DOMAIN: ''
      WHOISXMLAPI_API_KEY: ''
      AUTO_CREATE_RCA: 'false'
      CONFLUENCE_API_URL: 'false'
      CONFLUENCE_API_USERNAME: ''
      CONFLUENCE_API_TOKEN: ''
      CONFLUENCE_SPACE: ''
      CONFLUENCE_PARENT_PAGE: ''
      DEFAULT_WEB_ADMIN_PASSWORD: 'foobar1234'
      JWT_SECRET_KEY: 'supersecret'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    links:
      - incidentxbot_db
  incidentxbot_db:
    image: postgres:13
    command:
      ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']
    hostname: db
    environment:
      POSTGRES_PASSWORD: 'somepasswordxx'
      POSTGRES_USER: 'incidentxbot'
    ports:
      - 5432:5432
